"""initial migration with column change and teacher table added 

Revision ID: 17a78ecc2b34
Revises: 
Create Date: 2024-05-11 11:45:39.255839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17a78ecc2b34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('register_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('picture_uri',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('picture_uri', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('department', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('nrc', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('father_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('phone_no', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('register_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('register_date')
        batch_op.drop_column('email')
        batch_op.drop_column('phone_no')
        batch_op.drop_column('address')
        batch_op.drop_column('father_name')
        batch_op.drop_column('nrc')
        batch_op.drop_column('position')
        batch_op.drop_column('department')
        batch_op.drop_column('picture_uri')
        batch_op.drop_column('name')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('picture_uri',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('register_date')

    # ### end Alembic commands ###
