"""added: TrackPass table for in and out track

Revision ID: 7b7b5e13cfcc
Revises: 17a78ecc2b34
Create Date: 2024-05-12 11:10:13.352941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7b5e13cfcc'
down_revision = '17a78ecc2b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trackpass', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('out_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'teacher', ['teacher_id'], ['teacher_id'])
        batch_op.create_foreign_key(None, 'student', ['student_id'], ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trackpass', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('student_id')
        batch_op.drop_column('out_time')
        batch_op.drop_column('in_time')

    # ### end Alembic commands ###
